# Generated by Django 4.2.6 on 2023-11-09 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0006_product_product_id_alter_product_product_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
