# Generated by Django 4.2.6 on 2023-11-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0009_alter_product_product_img_alter_product_product_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
